version: '3'
services:
    phase2:
        stdin_open: true
        
        tty: true

        build:
            context: .
            dockerfile: dockerfile

        container_name: phase2

        ports:
            - "51966:51966"
            - "51967:51967"

        volumes:
            # (src) : (dest)
            - "./:/phase2"
