FROM ubuntu:22.04

RUN mkdir -p /phase2 
RUN apt update 
RUN apt install -y python3.11 python3-pip nginx
RUN pip3 install Flask
RUN pip3 install Flask-SocketIO 

WORKDIR /phase2

# CMD ["python3.11", "./server.py"]